platform :ios, '8.0'
use_frameworks!
target 'MuseumGuide2.0' do
pod 'CocoaLumberjack'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'ReactiveCocoa','2.5'
pod 'MJRefresh', '~> 3.1.12'
pod 'MJExtension', '~> 3.0.13'
pod 'Masonry', '~> 1.0.2'
pod 'SDCycleScrollView', '~> 1.65'
pod 'DACircularProgress', '~> 2.3.1'
pod 'SDWebImage/WebP'

end
